dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    token:
      secure: "OWPfOKRIV1VDQ0etoAntyQiy7YVmNa4iB8Vos5d6fEybw4jt8FveA19aotH5Qs/pxODkxlDnasQxdQF3oAU45WvnMzsmbudI+zIKsf9NguUMoazj5hiV0eopBgVSKjy8uNlH102RrpQt27bsyL/n8w9KFB+a6f+IiXUNlQlPDC8fcsin70RaO1GrzvtwvxHUbYSGDfm3+hEDf99x/85g8osFIh82QXtat2K37hBZnl7YK5cCbScRXG+rw20zHwDFn2zX5VyC95aWDtCpuouybsn1sJBF1tpBlepIZfs2OODp4Xy50LcD/CyEpRvp64QKL+vhXIMRk8PrGvUGN9Zh4UyBgvWbouJwFjgZJ7gbAhin49sdxHDSepug5Qun2OstitIVmx3qJkNGjOgBm9BI3TE5lOp1TbDCHoL4mlhh5yUyAo755SrrbcZFduDAtcAA5bgBqSCMEVVVXi3f/1mg+4gvrLeS84oFzTCw6cXRLtoLBd2nOy8iCKBY0Mv7Z1x4rNpym9YPQJZuvCwvSO/MYphEsYlclrfV4fxyRfoxMbL1MRkaj8A+vbRKjz67n3t/QnwFONpnuiRuWZTILrp8KhsQ+xKlCRMcyVodLmsy+AD9EyJJm9je7M5jQBAsyNZhViWj1GTWAJv1FyjtKsPEz/fegex6s+oMGvsKaN3e7Iw="
    branches:
      - master
      - develop
script:
  - sonar-scanner
