dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: "hhu-stups"
    token:
      secure: "aKORsOj3mtb5hjETiIEVF72n+eBBaWesbxmod7E8pBk2w2vIf1en9+/00uC3C1xNCeEBpIGSvcmfXZqgHycVSctrDWI1lH9zSRYDnrHZjEOznWaCjR6lzgn7ParAoJvvqS1vGgyA6+pCtnkHBrL4WDhuhODm9k/KziuW6JAuGvLK/xF8dO/wxRtrcMf4bzcJs55cnr4bCX8FE3tQpSPnM9r7n20NEzw7vwi2TQG0rRjRrtHfWT+T7CH1qX1soym1b/TwyuraBAB6//qXqZyxp8pMPf0hXeT7sjj2SPOFqeXiPcdrNZZpqxGXFmZccnseppVZ5LU4Oyss/UDXFCx309rQafcejD0116uEZvHOammSdMNdQmmIRlWgyeQvb/Bp1CpcUj+xNocF99okZMoI4A8+ajFOnbVsUxtDzbBawLjTFbhgSqdPkFtv7rVSpe1svcoAzSCzO/NlNjiCqgDjX0STTAS7dd3trIU9nghCNFQNatzgSxmPdmTvePEiphbMTmrFsOJOwCtsdAtHA2fk3psBpmHa9P8TM1/s0oj6ReGKmVwfhLeWgfR1fBg92iNbOqIslyJ0hOFx0Qd52D4V+XLSHBbE20IrHUpbEH0mQt0I4yL1uXonnWl81kz6AKUNNER6o4ut5pQUHOqOS4I64d/8USw138AYuK0yB0qK7sQ="
    branches:
    - master
    - develop
script:
- ./gradlew check
- sonar-scanner
