dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: "hhu-stups"
    branches:
    - master
    - develop
script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
env:
  global:
    secure: yOHVDByQqCeu1ZOA2nCi7RKvH+CuDkSkHDXy6D+hNh75Ovm7dQewFmL/G7ITK308H2QEGajcXTo6Sk4dzm2MfxhwctOsTMfUkJHDcHhiPdbTgxzSLA5OK38haZaU8Gie3rbRubTPaj3ttKGeROncW7aYOSubAlz1c7vkLEofQvSjNbXlEtnBeVUu7JjM/ALJNqq1uo5q2h5SByktzzGHr6g9hlyRzIgaz2PJIYhk1FdqTqlhhUPe8xmGzpPS2Eh/bAKMyvq5ov3oVePHDzcW2apJkbhcMT4u4FOiTZYk71xAEcAm760fT5hmHEQ+KGCMc82tYQXEIRNO0KI+k9SviD8cSlbEYhBT39UmRs6uSEzMz1hk92DWRTgLzrNP/SFuXMLrRWa4TArJwyTIlkZjI18meSUpH/lx1BYCOwit1ggIklLjq50rBvX+FHkxFbJ0gj3nC8Ut2unR8ErGzzbDTHleRERSs6E1d4jWTBl1vy/WQRBFVYZkJaubKonuMHsnjBBwXvJvRtw5TPRiCUAYAUdWZHPaMJJhv7f/8HvLqA3z0IC8S0Ta7QlONjpZcva6mh16GZFbqjVtCVPUE0i1L6pLDhs+2BTZqLyqG4mc68NeaZBHL6QCKOgqFCY91k8yS2EkPMXQ6qZTyNsRXt6RXDpbB+Zvj3xHQdOvWimyVgU=
